### PR TITLE
Allow test or get when target is readable but not writable

### PR DESCRIPTION
**Pull request by zmwangx**
Test or get should not need write permissions. On the other hand, I don't see a subcommand named "extract". Might be an outdated name.

I also removed trailing whitespace along the way.

### CODE REVIEW

**Comment by mklement0** [comment]
Thanks again - I incorporated some of you changes in to v0.1.7, which I've just published to the npm registry.

I didn't use your PR directly, because the trailing whitespace in the man source _was_ significant - the two trailing spaces specify an intentional line break.

However, I've added you to the `package.json` file as a contributor.

**Comment by zmwangx** [comment]
> I didn't use your PR directly, because the trailing whitespace in the man source was significant - the two trailing spaces specify an intentional line break.

Sorry for the blanket trimming, I didn't pay attention to that part.

**Comment by mklement0** [comment]
No worries - I appreciate your efforts - good stuff.

**Comment by zmwangx** [comment]
By the way, may I ask you why you put hard line breaks in the man source? You can just let `groff` soft-wrap it for you, which is the case for most if not all manpages I've seen. Hard line breaks are also not friendly to terminals < 80 columns.

**Comment by mklement0** [comment]
Honestly, I just assumed everyone's terminal has at least 80 columns.

The hard line breaks are for cases where `man` is not available, and the source must be rendered as-is, such as when installing an npm package on Windows.

Where would you still come across terminals with less than 80 columns (I'm asking innocently)?

**Comment by zmwangx** [comment]
> Where would you still come across terminals with less than 80 columns

The most common place is tmux with multiple panes. iTerm2 split panes to the same effect.

**Comment by mklement0** [comment]
Got it. I personally never use these.

Given that I do want the plain-text rendering to work as it does now, I'm not sure there's a good solution.

**Comment by zmwangx** [comment]
Not a big deal.

**Pull request closed without merging**
